// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtq7VBYJ4vR0mraiC0mLTWgL9VkfOVzBw',
    appId: '1:337643368519:web:20343d84836cc87ff30162',
    messagingSenderId: '337643368519',
    projectId: 'brew-crew-b09eb',
    authDomain: 'brew-crew-b09eb.firebaseapp.com',
    storageBucket: 'brew-crew-b09eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmPOePvtDZeIK2vH3qhD3wRwdN9X2AfU8',
    appId: '1:337643368519:android:8b68f08b4b74de08f30162',
    messagingSenderId: '337643368519',
    projectId: 'brew-crew-b09eb',
    storageBucket: 'brew-crew-b09eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUkrtRGGEl74APkWCf6t-K5-LT_5C57xg',
    appId: '1:337643368519:ios:af29be65dad0ba30f30162',
    messagingSenderId: '337643368519',
    projectId: 'brew-crew-b09eb',
    storageBucket: 'brew-crew-b09eb.appspot.com',
    iosClientId: '337643368519-71ivgn4ohvlofeknm5eemcnu5c2iofjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
